#!/bin/sh
# wait a little first... (you can still change windows with Command+Tab)
echo sleeping...
sleep 0.5

# check the Screenshots that are there yet
OLD_FILE_NAMES=$(ls -1 ~/Desktop/Screenshot*|tail -1)
# take screenshot first
echo "tell application \"System Events\" to key code 21 using {shift down, command down}" | osascript
# now check if a Screenshot was created on the Desktop
NEW_FILENAMES=$(ls -1 ~/Desktop/Screenshot*|tail -1)
# if not, wait and check again
while test "$OLD_FILE_NAMES" = "$NEW_FILENAMES";
do
    sleep 1
    NEW_FILENAMES=$(ls -1 ~/Desktop/Screenshot*|tail -1)
done

# then find newest screenshot
FILE_NAME=$(ls -1 ~/Desktop/Screenshot*|tail -1)
# Write an Applescript that uses preview to OCR

cat << EOF > /tmp/ocrimage.scpt
use framework "Vision"

on getImageText(imagePath)
    -- Get image content
    set theImage to current application's NSImage's alloc()'s initWithContentsOfFile:imagePath

     -- Set up request handler using image's raw data
    set requestHandler to current application's VNImageRequestHandler's alloc()'s initWithData:(theImage's TIFFRepresentation()) options:(current application's NSDictionary's alloc()'s init())
    
    -- Initialize text request
    set theRequest to current application's VNRecognizeTextRequest's alloc()'s init()
  
     -- Perform the request and get the results
    requestHandler's performRequests:(current application's NSArray's arrayWithObject:(theRequest)) |error|:(missing value)
    set theResults to theRequest's results()

    -- Obtain and return the string values of the results
    set theText to {}
    repeat with observation in theResults
        copy ((first item in (observation's topCandidates:1))'s |string|() as text) to end of theText
    end repeat
    return theText
end getImageText

on run (argv)
    if (count of argv) is 0 then error "Must provide an image path"
    getImageText(item 1 of argv)
end run

EOF

# OCR with preview
OCR_CONTENT=$(osascript /tmp/ocrimage.scpt "$FILE_NAME")

# put result on the command line
echo "$OCR_CONTENT"

# copy result to clipboard
echo "$OCR_CONTENT"|pbcopy 

# move screenshot to different name so we know this was an OCR screenshot
mv "$FILE_NAME" "$FILE_NAME.ocr.png"
